swagger: "2.0"
info:
  version: "1.0.0"
  title: Express & Expro Example Swagger Doc
  description: |
    Online shopping server api example to demonstrate the usage of expro with express.
host: localhost:3000
# basePath prefixes all resource paths
basePath: /api/v1
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
  - application/xml
# format of the responses to the client (Accepts)
produces:
  - application/json
  - application/xml

definitions:

  ApiResult:
    additionalProperties: true
    properties:
      code:
        type: integer
        default: 200
      result:
        type: string
        default: OK
  ApiErrorResult:
    properties:
      code:
        type: integer
        default: 500
      error:
        $ref: "#/definitions/ApiError"
  ApiError:
    properties:
      code:
        type: string
      message:
        type: string

responses:
  ApiResponse:
    description: Success
    schema:
      $ref: "#/definitions/ApiResult"
  ApiErrorResponse:
    description: Error
    schema:
      $ref: "#/definitions/ApiErrorResult"