swagger: "2.0"
info:
  version: "1.0.0"
  title: Express & Expro Example Swagger Doc
  description: |
    Online shopping server api example to demonstrate the usage of expro with express.
host: localhost:3000
# basePath prefixes all resource paths
basePath: /api/v1
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
  - application/xml
# format of the responses to the client (Accepts)
produces:
  - application/json
  - application/xml

definitions:
  Pagination:
    properties:
      pageIndex:
        type: integer
        minimum: 1
      pageSize:
        type: integer
        minimum: 1
      totalPageCount:
        type: integer
        minimum: 0
      totalItemCount:
        type: integer
        minimum: 0
  ErrorResult:
    properties:
      error:
        $ref: "#/definitions/Error"
  Error:
    properties:
      code:
        type: string
        description: error code
      message:
        type: string
        description: error message

responses:
  ErrorResponse:
    description: Error
    schema:
      $ref: "#/definitions/ErrorResult"